### ISSUE TITLE
自增组件联动

### ISSUE THREAD

**Issue by 2733711860** [xinnian999/vue-form-craft#13]
自增组件  子组件1(name1)发生变化，清空子组件2(name2)的值。这种联动如何实现？我通过$item.name2=""，无法清空数据

**Comment by xinnian999** [comment]
这个貌似还不太支持，等有时间了我会扩展一下

**Comment by hqinghang** [comment]
这个功能有扩展完成吗

**Comment by hqinghang** [comment]
> 这个貌似还不太支持，等有时间了我会扩展一下

这个功能扩展完成了吗

**Comment by xinnian999** [comment]
https://xinnian999.github.io/vue-form-craft/zh/linkage.html 已扩展
