### ISSUE TITLE
当表单组件超出200个之后，输入的时候会有明显卡顿的问题

### ISSUE THREAD

**Issue by duanxingyu** [xinnian999/vue-form-craft#17]
在渲染多表单组件的场景下，目前测了下渲染300个组件，然后操作表单组件，如在文本框中快速输入信息，就会出现肉眼卡顿的问题，内存飙升。
![Uploading test.gif…]()

**Comment by duanxingyu** [comment]
![Uploading test.gif…]()

**Comment by xinnian999** [comment]
我试了一下没有明显卡顿，可以把你schema发给我一份测试吗，发我邮箱3307578337@qq.com
