### ISSUE TITLE
配置关联有问题,值不解析

### ISSUE THREAD

**Issue by towyears** [xinnian999/vue-form-craft#23]
![image](https://github.com/user-attachments/assets/7c182681-dd2e-467f-925f-9b817789371f)

**Comment by xinnian999** [comment]
form-goods换成驼峰命名再试一下。你这样js应该不会解析

**Comment by xinnian999** [comment]
或者这样 {{ $selectData['form-goods'].price }}

**Comment by towyears** [comment]
![image](https://github.com/user-attachments/assets/d5ef8dd4-2a51-4545-9478-caf4496c1374)
![image](https://github.com/user-attachments/assets/d960f2ef-1786-4aa9-a32b-e8f707821324)

**Comment by towyears** [comment]
selectData 是个[object Object], 在下一级就成字符串了

**Comment by towyears** [comment]
{{ $selectData['form_goods'] }} 为空了,文本框显示空

**Comment by xinnian999** [comment]
jsonSchema 贴一下。我试试

**Comment by towyears** [comment]
{
  "labelWidth": 150,
  "labelAlign": "right",
  "size": "default",
  "items": [
    {
      "label": "多行文本",
      "component": "Textarea",
      "props": {
        "autosize": {
          "minRows": 4,
          "maxRows": 999
        },
        "placeholder": "请输入..."
      },
      "designKey": "design-yX15",
      "name": "form-text"
    },
    {
      "label": "商品",
      "component": "Select",
      "props": {
        "mode": "static",
        "options": [
          {
            "label": "商品1",
            "value": "1",
            "price": 20
          },
          {
            "label": "商品2",
            "value": "2",
            "price": 22
          },
          {
            "label": "商品3",
            "value": "3",
            "price": 24
          }
        ],
        "placeholder": "please select..."
      },
      "designKey": "design-6Dj0",
      "name": "form_goods",
      "change": [
        {
          "target": "form-text",
          "value": "{{ $selectData['form_goods'].price }}"
        }
      ]
    },
    {
      "label": "姓名",
      "component": "Input",
      "props": {
        "placeholder": "请输入文本"
      },
      "designKey": "design-YYB3",
      "name": "user_name"
    },
    {
      "label": "简介",
      "component": "Textarea",
      "props": {
        "autosize": {
          "minRows": 4,
          "maxRows": 999
        },
        "placeholder": "{{ $values.user_name + '的简介' }}"
      },
      "designKey": "design-uHAF",
      "name": "user_desc"
    }
  ]
}

**Comment by towyears** [comment]
{
  "labelWidth": 150,
  "labelAlign": "right",
  "size": "default",
  "items": [
    {
      "label": "多行文本",
      "component": "Textarea",
      "props": {
        "autosize": {
          "minRows": 4,
          "maxRows": 999
        },
        "placeholder": "请输入..."
      },
      "designKey": "design-yX15",
      "name": "form-text"
    },
    {
      "label": "商品",
      "component": "Select",
      "props": {
        "mode": "static",
        "options": [
          {
            "label": "商品1",
            "value": "1",
            "price": 20
          },
          {
            "label": "商品2",
            "value": "2",
            "price": 22
          },
          {
            "label": "商品3",
            "value": "3",
            "price": 24
          }
        ],
        "placeholder": "please select..."
      },
      "designKey": "design-6Dj0",
      "name": "form_goods",
      "change": [
        {
          "target": "form-text",
          "value": "{{ $selectData['form_goods'].price }}"
        }
      ]
    },
    {
      "label": "姓名",
      "component": "Input",
      "props": {
        "placeholder": "请输入文本"
      },
      "designKey": "design-YYB3",
      "name": "user_name"
    },
    {
      "label": "简介",
      "component": "Textarea",
      "props": {
        "autosize": {
          "minRows": 4,
          "maxRows": 999
        },
        "placeholder": "{{ $values.user_name + '的简介' }}"
      },
      "designKey": "design-uHAF",
      "name": "user_desc"
    }
  ]
}

**Comment by towyears** [comment]
![image](https://github.com/user-attachments/assets/c0fd4ecd-6ee4-42d9-aa37-65ebee98f1fb)
![image](https://github.com/user-attachments/assets/693baaf7-50e5-4f50-8195-d542f25f33e2)

**Comment by xinnian999** [comment]
应该是阅读模式有点bug，先不要切换阅读模式使用，等我修复一下

**Comment by xinnian999** [comment]
刚刚发布了v4.3.1 版本，把这个bug修了哈，可以更新一下

**Comment by towyears** [comment]
好的,亲.可以加一个电子签名的组件吗

**Comment by towyears** [comment]
就是类似这个的
![image](https://github.com/user-attachments/assets/23fe2d55-1837-48d9-a271-0b303e6ef0df)

**Comment by xinnian999** [comment]
好的，你先试试自己能不能通过自定义组件实现，等有时间我再扩展下

**Comment by xinnian999** [comment]
<img width="1440" alt="截屏2024-10-20 上午8 40 57" src="https://github.com/user-attachments/assets/585f0dea-f80d-4a50-a75d-2ce8eedd512e">
电子签名内置扩展了哈，最新版本v4.3.2
