### ISSUE TITLE
自定义电子签名组件怎么保存签名

### ISSUE THREAD

**Issue by towyears** [xinnian999/vue-form-craft#24]
![image](https://github.com/user-attachments/assets/82a0fb97-e959-4f6e-aebe-841ee2f21808)

**Comment by xinnian999** [comment]
在你组件内部接收v-model，可与表单数据建立绑定

**Comment by towyears** [comment]
好的,谢谢

**Comment by towyears** [comment]
![image](https://github.com/user-attachments/assets/3056a33b-e74f-47c4-8ec1-5a574121026c)
我找的这个现成的，好像他接收不到v-model。我一个后端弄这个太难受了

**Comment by towyears** [comment]
这个自定义的组件怎么在左侧显示呢

**Comment by xinnian999** [comment]
> 这个自定义的组件怎么在左侧显示呢

https://xinnian999.github.io/vue-form-craft/zh/extend.html

**Comment by xinnian999** [comment]
> ![image](https://private-user-images.githubusercontent.com/30588249/378038799-3056a33b-e74f-47c4-8ec1-5a574121026c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMDM1NTIsIm5iZiI6MTcyOTMwMzI1MiwicGF0aCI6Ii8zMDU4ODI0OS8zNzgwMzg3OTktMzA1NmEzM2ItZTc0Zi00N2M0LThlYzEtNWE1NzQxMjEwMjZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDAyMDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjYTlkNTc3ZjAwYjY3MTJmYjgyY2MyMTllODcwMGUyZGRjYzVlYWI2MDU1OTEyYjYxZDhjMTJiZWZhNDdiMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OFUVNpQjyfTg_qHXE9i4gJf_8sbCgnNvI6BEmGOOF2g) 我找的这个现成的，好像他接收不到v-model。我一个后端弄这个太难受了

我查阅了一下这个组件，确实不能接受v-model。它只能通过生成签名图片的回调函数里，拿到图片数据，再通过vue的defineModel，来保存数据

**Comment by towyears** [comment]
![image](https://github.com/user-attachments/assets/4d98bffc-3dcd-4bf3-8c87-dc68c4a17a9d)
v-model 写这里了。保存的base64图标赋值给他

**Comment by xinnian999** [comment]
解决了？

**Comment by towyears** [comment]
可以拿到base64图了
